services:
  rethinkdb:
    image: kudarap/rethinkdb:2.4
    ports:
      - "28015:28015"
      - "8080:8080"
    volumes:
      - ./.localdata/postgres:/var/lib/postgresql/data'

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: root
    volumes:
      - ./.localdata/postgres:/var/lib/postgresql/data'
