services:
  rethinkdb:
    image: kudarap/rethinkdb:2.4
    ports:
      - "28015:28015"
      - "8080:8080"
    volumes:
      - ./.localdata/rethinkdb:/data'

  redis:
    image: redis:8.0
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: root
    volumes:
      - ./.localdata/redis:/data'
