// Code generated by "stringer -type=Errors -output=errors_string.go"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AuthErrNotFound-1000]
	_ = x[AuthErrRequiredID-1001]
	_ = x[AuthErrRequiredFields-1002]
	_ = x[AuthErrNoAccess-1003]
	_ = x[AuthErrLogin-1004]
	_ = x[AuthErrRefreshToken-1005]
}

const _Errors_name = "AuthErrNotFoundAuthErrRequiredIDAuthErrRequiredFieldsAuthErrNoAccessAuthErrLoginAuthErrRefreshToken"

var _Errors_index = [...]uint8{0, 15, 32, 53, 68, 80, 99}

func (i Errors) String() string {
	i -= 1000
	if i >= Errors(len(_Errors_index)-1) {
		return "Errors(" + strconv.FormatInt(int64(i+1000), 10) + ")"
	}
	return _Errors_name[_Errors_index[i]:_Errors_index[i+1]]
}
