// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package phantasm

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson7c1f4c08DecodeGithubComKudarapDotagiftxPhantasm(in *jlexer.Lexer, out *inventory) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "assets":
			if in.IsNull() {
				in.Skip()
				out.Assets = nil
			} else {
				in.Delim('[')
				if out.Assets == nil {
					if !in.IsDelim(']') {
						out.Assets = make([]asset, 0, 0)
					} else {
						out.Assets = []asset{}
					}
				} else {
					out.Assets = (out.Assets)[:0]
				}
				for !in.IsDelim(']') {
					var v1 asset
					if in.IsNull() {
						in.Skip()
					} else {
						(v1).UnmarshalEasyJSON(in)
					}
					out.Assets = append(out.Assets, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "descriptions":
			if in.IsNull() {
				in.Skip()
				out.Descriptions = nil
			} else {
				in.Delim('[')
				if out.Descriptions == nil {
					if !in.IsDelim(']') {
						out.Descriptions = make([]description, 0, 0)
					} else {
						out.Descriptions = []description{}
					}
				} else {
					out.Descriptions = (out.Descriptions)[:0]
				}
				for !in.IsDelim(']') {
					var v2 description
					if in.IsNull() {
						in.Skip()
					} else {
						(v2).UnmarshalEasyJSON(in)
					}
					out.Descriptions = append(out.Descriptions, v2)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "total_inventory_count":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TotalInventoryCount = int(in.Int())
			}
		case "last_assetid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastAssetID = string(in.String())
			}
		case "more_items":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MoreItems = int(in.Int())
			}
		case "rwgrsn":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Rwgrsn = int(in.Int())
			}
		case "success":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Success = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7c1f4c08EncodeGithubComKudarapDotagiftxPhantasm(out *jwriter.Writer, in inventory) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"assets\":"
		out.RawString(prefix[1:])
		if in.Assets == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v3, v4 := range in.Assets {
				if v3 > 0 {
					out.RawByte(',')
				}
				(v4).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"descriptions\":"
		out.RawString(prefix)
		if in.Descriptions == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.Descriptions {
				if v5 > 0 {
					out.RawByte(',')
				}
				(v6).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"total_inventory_count\":"
		out.RawString(prefix)
		out.Int(int(in.TotalInventoryCount))
	}
	{
		const prefix string = ",\"last_assetid\":"
		out.RawString(prefix)
		out.String(string(in.LastAssetID))
	}
	{
		const prefix string = ",\"more_items\":"
		out.RawString(prefix)
		out.Int(int(in.MoreItems))
	}
	{
		const prefix string = ",\"rwgrsn\":"
		out.RawString(prefix)
		out.Int(int(in.Rwgrsn))
	}
	{
		const prefix string = ",\"success\":"
		out.RawString(prefix)
		out.Int(int(in.Success))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v inventory) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7c1f4c08EncodeGithubComKudarapDotagiftxPhantasm(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v inventory) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7c1f4c08EncodeGithubComKudarapDotagiftxPhantasm(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *inventory) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7c1f4c08DecodeGithubComKudarapDotagiftxPhantasm(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *inventory) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7c1f4c08DecodeGithubComKudarapDotagiftxPhantasm(l, v)
}
func easyjson7c1f4c08DecodeGithubComKudarapDotagiftxPhantasm1(in *jlexer.Lexer, out *descriptionAttrs) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "value":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Value = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7c1f4c08EncodeGithubComKudarapDotagiftxPhantasm1(out *jwriter.Writer, in descriptionAttrs) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix)
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"value\":"
		out.RawString(prefix)
		out.String(string(in.Value))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v descriptionAttrs) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7c1f4c08EncodeGithubComKudarapDotagiftxPhantasm1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v descriptionAttrs) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7c1f4c08EncodeGithubComKudarapDotagiftxPhantasm1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *descriptionAttrs) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7c1f4c08DecodeGithubComKudarapDotagiftxPhantasm1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *descriptionAttrs) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7c1f4c08DecodeGithubComKudarapDotagiftxPhantasm1(l, v)
}
func easyjson7c1f4c08DecodeGithubComKudarapDotagiftxPhantasm2(in *jlexer.Lexer, out *description) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "appid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AppID = int(in.Int())
			}
		case "background_color":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BackgroundColor = string(in.String())
			}
		case "classid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ClassID = string(in.String())
			}
		case "commodity":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Commodity = int(in.Int())
			}
		case "currency":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Currency = int(in.Int())
			}
		case "descriptions":
			if in.IsNull() {
				in.Skip()
				out.Descriptions = nil
			} else {
				in.Delim('[')
				if out.Descriptions == nil {
					if !in.IsDelim(']') {
						out.Descriptions = make([]descriptionAttrs, 0, 1)
					} else {
						out.Descriptions = []descriptionAttrs{}
					}
				} else {
					out.Descriptions = (out.Descriptions)[:0]
				}
				for !in.IsDelim(']') {
					var v7 descriptionAttrs
					if in.IsNull() {
						in.Skip()
					} else {
						(v7).UnmarshalEasyJSON(in)
					}
					out.Descriptions = append(out.Descriptions, v7)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "icon_url":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IconURL = string(in.String())
			}
		case "icon_url_large":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IconURLLarge = string(in.String())
			}
		case "instanceid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.InstanceID = string(in.String())
			}
		case "market_hash_name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MarketHashName = string(in.String())
			}
		case "market_marketable_restriction":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MarketMarketableRestriction = int(in.Int())
			}
		case "market_name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MarketName = string(in.String())
			}
		case "market_tradable_restriction":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MarketTradableRestriction = int(in.Int())
			}
		case "marketable":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Marketable = int(in.Int())
			}
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "name_color":
			if in.IsNull() {
				in.Skip()
			} else {
				out.NameColor = string(in.String())
			}
		case "tags":
			if in.IsNull() {
				in.Skip()
				out.Tags = nil
			} else {
				in.Delim('[')
				if out.Tags == nil {
					if !in.IsDelim(']') {
						out.Tags = make([]struct {
							Category              string `json:"category"`
							Color                 string `json:"color,omitempty"`
							InternalName          string `json:"internal_name"`
							LocalizedCategoryName string `json:"localized_category_name"`
							LocalizedTagName      string `json:"localized_tag_name"`
						}, 0, 0)
					} else {
						out.Tags = []struct {
							Category              string `json:"category"`
							Color                 string `json:"color,omitempty"`
							InternalName          string `json:"internal_name"`
							LocalizedCategoryName string `json:"localized_category_name"`
							LocalizedTagName      string `json:"localized_tag_name"`
						}{}
					}
				} else {
					out.Tags = (out.Tags)[:0]
				}
				for !in.IsDelim(']') {
					var v8 struct {
						Category              string `json:"category"`
						Color                 string `json:"color,omitempty"`
						InternalName          string `json:"internal_name"`
						LocalizedCategoryName string `json:"localized_category_name"`
						LocalizedTagName      string `json:"localized_tag_name"`
					}
					easyjson7c1f4c08Decode(in, &v8)
					out.Tags = append(out.Tags, v8)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "tradable":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Tradable = int(in.Int())
			}
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7c1f4c08EncodeGithubComKudarapDotagiftxPhantasm2(out *jwriter.Writer, in description) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"appid\":"
		out.RawString(prefix[1:])
		out.Int(int(in.AppID))
	}
	{
		const prefix string = ",\"background_color\":"
		out.RawString(prefix)
		out.String(string(in.BackgroundColor))
	}
	{
		const prefix string = ",\"classid\":"
		out.RawString(prefix)
		out.String(string(in.ClassID))
	}
	{
		const prefix string = ",\"commodity\":"
		out.RawString(prefix)
		out.Int(int(in.Commodity))
	}
	{
		const prefix string = ",\"currency\":"
		out.RawString(prefix)
		out.Int(int(in.Currency))
	}
	{
		const prefix string = ",\"descriptions\":"
		out.RawString(prefix)
		if in.Descriptions == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v9, v10 := range in.Descriptions {
				if v9 > 0 {
					out.RawByte(',')
				}
				(v10).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"icon_url\":"
		out.RawString(prefix)
		out.String(string(in.IconURL))
	}
	{
		const prefix string = ",\"icon_url_large\":"
		out.RawString(prefix)
		out.String(string(in.IconURLLarge))
	}
	{
		const prefix string = ",\"instanceid\":"
		out.RawString(prefix)
		out.String(string(in.InstanceID))
	}
	{
		const prefix string = ",\"market_hash_name\":"
		out.RawString(prefix)
		out.String(string(in.MarketHashName))
	}
	{
		const prefix string = ",\"market_marketable_restriction\":"
		out.RawString(prefix)
		out.Int(int(in.MarketMarketableRestriction))
	}
	{
		const prefix string = ",\"market_name\":"
		out.RawString(prefix)
		out.String(string(in.MarketName))
	}
	{
		const prefix string = ",\"market_tradable_restriction\":"
		out.RawString(prefix)
		out.Int(int(in.MarketTradableRestriction))
	}
	{
		const prefix string = ",\"marketable\":"
		out.RawString(prefix)
		out.Int(int(in.Marketable))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"name_color\":"
		out.RawString(prefix)
		out.String(string(in.NameColor))
	}
	{
		const prefix string = ",\"tags\":"
		out.RawString(prefix)
		if in.Tags == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v11, v12 := range in.Tags {
				if v11 > 0 {
					out.RawByte(',')
				}
				easyjson7c1f4c08Encode(out, v12)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"tradable\":"
		out.RawString(prefix)
		out.Int(int(in.Tradable))
	}
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix)
		out.String(string(in.Type))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v description) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7c1f4c08EncodeGithubComKudarapDotagiftxPhantasm2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v description) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7c1f4c08EncodeGithubComKudarapDotagiftxPhantasm2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *description) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7c1f4c08DecodeGithubComKudarapDotagiftxPhantasm2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *description) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7c1f4c08DecodeGithubComKudarapDotagiftxPhantasm2(l, v)
}
func easyjson7c1f4c08Decode(in *jlexer.Lexer, out *struct {
	Category              string `json:"category"`
	Color                 string `json:"color,omitempty"`
	InternalName          string `json:"internal_name"`
	LocalizedCategoryName string `json:"localized_category_name"`
	LocalizedTagName      string `json:"localized_tag_name"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "category":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Category = string(in.String())
			}
		case "color":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Color = string(in.String())
			}
		case "internal_name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.InternalName = string(in.String())
			}
		case "localized_category_name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LocalizedCategoryName = string(in.String())
			}
		case "localized_tag_name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LocalizedTagName = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7c1f4c08Encode(out *jwriter.Writer, in struct {
	Category              string `json:"category"`
	Color                 string `json:"color,omitempty"`
	InternalName          string `json:"internal_name"`
	LocalizedCategoryName string `json:"localized_category_name"`
	LocalizedTagName      string `json:"localized_tag_name"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"category\":"
		out.RawString(prefix[1:])
		out.String(string(in.Category))
	}
	if in.Color != "" {
		const prefix string = ",\"color\":"
		out.RawString(prefix)
		out.String(string(in.Color))
	}
	{
		const prefix string = ",\"internal_name\":"
		out.RawString(prefix)
		out.String(string(in.InternalName))
	}
	{
		const prefix string = ",\"localized_category_name\":"
		out.RawString(prefix)
		out.String(string(in.LocalizedCategoryName))
	}
	{
		const prefix string = ",\"localized_tag_name\":"
		out.RawString(prefix)
		out.String(string(in.LocalizedTagName))
	}
	out.RawByte('}')
}
func easyjson7c1f4c08DecodeGithubComKudarapDotagiftxPhantasm3(in *jlexer.Lexer, out *asset) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "amount":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Amount = string(in.String())
			}
		case "appid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AppID = int(in.Int())
			}
		case "assetid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AssetID = string(in.String())
			}
		case "classid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ClassID = string(in.String())
			}
		case "contextid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ContextID = string(in.String())
			}
		case "instanceid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.InstanceID = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7c1f4c08EncodeGithubComKudarapDotagiftxPhantasm3(out *jwriter.Writer, in asset) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"amount\":"
		out.RawString(prefix[1:])
		out.String(string(in.Amount))
	}
	{
		const prefix string = ",\"appid\":"
		out.RawString(prefix)
		out.Int(int(in.AppID))
	}
	{
		const prefix string = ",\"assetid\":"
		out.RawString(prefix)
		out.String(string(in.AssetID))
	}
	{
		const prefix string = ",\"classid\":"
		out.RawString(prefix)
		out.String(string(in.ClassID))
	}
	{
		const prefix string = ",\"contextid\":"
		out.RawString(prefix)
		out.String(string(in.ContextID))
	}
	{
		const prefix string = ",\"instanceid\":"
		out.RawString(prefix)
		out.String(string(in.InstanceID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v asset) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7c1f4c08EncodeGithubComKudarapDotagiftxPhantasm3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v asset) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7c1f4c08EncodeGithubComKudarapDotagiftxPhantasm3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *asset) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7c1f4c08DecodeGithubComKudarapDotagiftxPhantasm3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *asset) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7c1f4c08DecodeGithubComKudarapDotagiftxPhantasm3(l, v)
}
func easyjson7c1f4c08DecodeGithubComKudarapDotagiftxPhantasm4(in *jlexer.Lexer, out *Service) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7c1f4c08EncodeGithubComKudarapDotagiftxPhantasm4(out *jwriter.Writer, in Service) {
	out.RawByte('{')
	first := true
	_ = first
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Service) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7c1f4c08EncodeGithubComKudarapDotagiftxPhantasm4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Service) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7c1f4c08EncodeGithubComKudarapDotagiftxPhantasm4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Service) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7c1f4c08DecodeGithubComKudarapDotagiftxPhantasm4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Service) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7c1f4c08DecodeGithubComKudarapDotagiftxPhantasm4(l, v)
}
func easyjson7c1f4c08DecodeGithubComKudarapDotagiftxPhantasm5(in *jlexer.Lexer, out *CrawlSummary) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "elapsed_sec":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ElapsedSec = float64(in.Float64())
			}
		case "inventory_count":
			if in.IsNull() {
				in.Skip()
			} else {
				out.InventoryCount = int(in.Int())
			}
		case "parts":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Parts = int(in.Int())
			}
		case "query_limit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.QueryLimit = int(in.Int())
			}
		case "request_delay_ms":
			if in.IsNull() {
				in.Skip()
			} else {
				out.RequestDelayMs = int(in.Int())
			}
		case "steam_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SteamID = string(in.String())
			}
		case "webhook_url":
			if in.IsNull() {
				in.Skip()
			} else {
				out.WebhookURL = string(in.String())
			}
		case "precheck":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Precheck = bool(in.Bool())
			}
		case "precheck_hash":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PrecheckHash = string(in.String())
			}
		case "last_asset_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastAssetID = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7c1f4c08EncodeGithubComKudarapDotagiftxPhantasm5(out *jwriter.Writer, in CrawlSummary) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"elapsed_sec\":"
		out.RawString(prefix[1:])
		out.Float64(float64(in.ElapsedSec))
	}
	{
		const prefix string = ",\"inventory_count\":"
		out.RawString(prefix)
		out.Int(int(in.InventoryCount))
	}
	{
		const prefix string = ",\"parts\":"
		out.RawString(prefix)
		out.Int(int(in.Parts))
	}
	{
		const prefix string = ",\"query_limit\":"
		out.RawString(prefix)
		out.Int(int(in.QueryLimit))
	}
	{
		const prefix string = ",\"request_delay_ms\":"
		out.RawString(prefix)
		out.Int(int(in.RequestDelayMs))
	}
	{
		const prefix string = ",\"steam_id\":"
		out.RawString(prefix)
		out.String(string(in.SteamID))
	}
	{
		const prefix string = ",\"webhook_url\":"
		out.RawString(prefix)
		out.String(string(in.WebhookURL))
	}
	{
		const prefix string = ",\"precheck\":"
		out.RawString(prefix)
		out.Bool(bool(in.Precheck))
	}
	{
		const prefix string = ",\"precheck_hash\":"
		out.RawString(prefix)
		out.String(string(in.PrecheckHash))
	}
	{
		const prefix string = ",\"last_asset_id\":"
		out.RawString(prefix)
		out.String(string(in.LastAssetID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CrawlSummary) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7c1f4c08EncodeGithubComKudarapDotagiftxPhantasm5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CrawlSummary) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7c1f4c08EncodeGithubComKudarapDotagiftxPhantasm5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CrawlSummary) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7c1f4c08DecodeGithubComKudarapDotagiftxPhantasm5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CrawlSummary) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7c1f4c08DecodeGithubComKudarapDotagiftxPhantasm5(l, v)
}
func easyjson7c1f4c08DecodeGithubComKudarapDotagiftxPhantasm6(in *jlexer.Lexer, out *Config) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "Addrs":
			if in.IsNull() {
				in.Skip()
				out.Addrs = nil
			} else {
				in.Delim('[')
				if out.Addrs == nil {
					if !in.IsDelim(']') {
						out.Addrs = make([]string, 0, 4)
					} else {
						out.Addrs = []string{}
					}
				} else {
					out.Addrs = (out.Addrs)[:0]
				}
				for !in.IsDelim(']') {
					var v13 string
					if in.IsNull() {
						in.Skip()
					} else {
						v13 = string(in.String())
					}
					out.Addrs = append(out.Addrs, v13)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "WebhookURL":
			if in.IsNull() {
				in.Skip()
			} else {
				out.WebhookURL = string(in.String())
			}
		case "Secret":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Secret = string(in.String())
			}
		case "Path":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Path = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7c1f4c08EncodeGithubComKudarapDotagiftxPhantasm6(out *jwriter.Writer, in Config) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Addrs\":"
		out.RawString(prefix[1:])
		if in.Addrs == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v14, v15 := range in.Addrs {
				if v14 > 0 {
					out.RawByte(',')
				}
				out.String(string(v15))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"WebhookURL\":"
		out.RawString(prefix)
		out.String(string(in.WebhookURL))
	}
	{
		const prefix string = ",\"Secret\":"
		out.RawString(prefix)
		out.String(string(in.Secret))
	}
	{
		const prefix string = ",\"Path\":"
		out.RawString(prefix)
		out.String(string(in.Path))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Config) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7c1f4c08EncodeGithubComKudarapDotagiftxPhantasm6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Config) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7c1f4c08EncodeGithubComKudarapDotagiftxPhantasm6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Config) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7c1f4c08DecodeGithubComKudarapDotagiftxPhantasm6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Config) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7c1f4c08DecodeGithubComKudarapDotagiftxPhantasm6(l, v)
}
