// Verified delivery and inventory

const VERIFIED_DELIVERY_NOHIT = 100
const VERIFIED_DELIVERY_NAME_VERIFIED = 200
const VERIFIED_DELIVERY_SENDER_VERIFIED = 300
const VERIFIED_DELIVERY_PRIVATE = 400
const VERIFIED_DELIVERY_ERROR = 500

export const VERIFIED_DELIVERY_MAP_TEXT = {
  [VERIFIED_DELIVERY_NOHIT]: 'Not found',
  [VERIFIED_DELIVERY_NAME_VERIFIED]: 'Item verified',
  [VERIFIED_DELIVERY_SENDER_VERIFIED]: 'Sender verified',
  [VERIFIED_DELIVERY_PRIVATE]: 'Private inventory',
  [VERIFIED_DELIVERY_ERROR]: 'Error',
}

const VERIFIED_INVENTORY_NOHIT = 100
const VERIFIED_INVENTORY_NAME_VERIFIED = 200
const VERIFIED_INVENTORY_PRIVATE = 400
const VERIFIED_INVENTORY_ERROR = 500

export const VERIFIED_INVENTORY_MAP_TEXT = {
  [VERIFIED_INVENTORY_NOHIT]: 'Not found',
  [VERIFIED_INVENTORY_NAME_VERIFIED]: 'Verified',
  [VERIFIED_INVENTORY_PRIVATE]: 'Private inventory',
  [VERIFIED_INVENTORY_ERROR]: 'Error',
}
