name: API production CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  HOST: root@chiligarlic.com
  IMAGE_NAME: dotagiftx/api
  IMAGE_FILE: api.tar
  WORKDIR: ~/dotagiftx/prod

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Compile
        run: make build

      - name: Test
        run: |
          go test -v ./
          go test -v ./gokit/...
          go test -v ./http/...
          go test -v ./steam/...
        #   go test -v ./verified/...

  deploy:
    # Ensure compile build passes before deploy
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Image
        run: docker build -t $IMAGE_NAME .

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: SSH Deploy
        run: |
          docker save -o $IMAGE_FILE $IMAGE_NAME
          scp $IMAGE_FILE $HOST:$WORKDIR/$IMAGE_FILE
          ssh $HOST "cd $WORKDIR && docker load -i $IMAGE_FILE"

#          ssh $HOST "cd $WORKDIR && docker load -i $IMAGE_FILE && ./restart.sh"
