root: true
extends:
  - eslint:recommended
  - airbnb
  - plugin:react/recommended
  - prettier
plugins:
  - react
  - prettier
env:
  browser: true
  es2020: true
parserOptions:
  ecmaVersion: 2020
rules:
  eqeqeq: off
  no-plusplus: off
  no-continue: off
  react/jsx-props-no-spreading: off
  react/jsx-closing-bracket-location: off
  react/forbid-prop-types: off
  react/jsx-filename-extension: off
  react/react-in-jsx-scope: off
  import/no-unresolved:
    - error
    - ignore:
        - '^@'
  import/extensions:
    - warn
    - ignore:
        - '^@'
  # temporarily off
  react/prop-types: warn
  react/require-default-props: warn
