---
extends:
  - airbnb
  - prettier
  - prettier/react
plugins:
  - prettier
rules:
  prettier/prettier: error
  no-plusplus: off
  no-continue: off
  react/jsx-props-no-spreading: off
  react/jsx-closing-bracket-location: off
  react/forbid-prop-types: off
  react/jsx-filename-extension: off
  react/react-in-jsx-scope: off
  import/no-unresolved:
    - error
    - ignore:
        - '^@'
